In [1]:
import pandas as pd

loading

read_csv, read_excel, DataFrame(dict) (from a dictionary)

In [2]:
df=pd.read_csv("orders.csv")
print(df)

    OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas Müller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country
0   1200.0  2024-06-01     Yes           USA
1    150.0  2024-06-03      No        Canada
2    300.0  2024-06-04     Yes           UAE
3     45.0  2024-06-05     Yes     Singapore
4     80.0  2024-06-06      No        Mexico
5      5.0  2024-06-07     Yes           UAE
6    450.0  2024-06-08     Yes            UK
7    220.0  2024-06-09      No   South Korea
8      1.5  2024-06-10     Yes         Italy
9     35.0  2024-06-11     Yes         Japan
10    85.0  2024-06-12     Yes        France
11   180.0  2024-06-13      No         India
12    12.0  2024-06-14     Yes     Australia
13    25.0  2024-06-15     Yes         Spain
14   280.0  2024-06-16      No         China
15     8.0  2024-06-17     Yes         Egypt
16    45.0  2024-06-18     Yes        Poland
17    65.0  2024-06-19      No           USA
18    15.0  2024-06-20     Yes         Japan
19   120.0  2024-06-21     Yes  Saudi Arabia
20     3.5  2024-06-22      No        Canada
21    95.0  2024-06-23     Yes        Brazil
22    35.0  2024-06-24     Yes       Germany
23     4.0  2024-06-25      No      Pakistan
24    28.0  2024-06-26     Yes        Sweden
25    75.0  2024-06-27     Yes        France
26    22.0  2024-06-28      No     Argentina
27     2.5  2024-06-29     Yes        Russia
28   110.0  2024-06-30     Yes   South Korea
29    18.0  2024-07-01      No         Italy
30    32.0  2024-07-02     Yes       Morocco
31   140.0  2024-07-03     Yes       Germany
32    42.0  2024-07-04      No      Colombia
33     0.8  2024-07-05     Yes           USA
34    55.0  2024-07-06     Yes         Japan
35    68.0  2024-07-07      No            UK
36   125.0  2024-07-08     Yes      Portugal
37    28.0  2024-07-09     Yes          Iran
38    18.0  2024-07-10      No   South Korea
39    35.0  2024-07-11     Yes       Ukraine

In [8]:
df.head() #first 5
df.tail() #last 5
df.info()
df.describe()
df.index

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     str
 2   Product       40 non-null     str
 3   Category      40 non-null     str
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     str
 7   Shipped       40 non-null     str
 8   Country       40 non-null     str
dtypes: float64(1), int64(2), str(6)
memory usage: 5.0 KB

RangeIndex(start=0, stop=40, step=1)

In [12]:
df[["Country","Product"]] #reference by columns
df.iloc[10] #reference by rows

OrderID                  1011
CustomerName    Sophie Martin
Product                Webcam
Category          Electronics
Quantity                    1
Price                    85.0
OrderDate          2024-06-12
Shipped                   Yes
Country                France
Name: 10, dtype: object

filtering

In [14]:
df[(df["Category"]=="Electronics") & (df["Country"]=="USA")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [16]:
df[df["CustomerName"].str.startswith("A")] #or endswith()
df[df["Country"].isin(["USA","Canada"])] #or notin()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

updating

In [18]:
df.loc[df["CustomerName"]=="Anna Ivanova", "Product"] = "xyz"
df.loc[df["CustomerName"]=="Anna Ivanova"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
39,1040,Anna Ivanova,xyz,Furniture,1,35.0,2024-07-11,Yes,Ukraine

deleting

In [ ]:
df.dropna() #drop rows with missing values

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,xyz,Furniture,1,35.0,2024-07-11,Yes,Ukraine

cleaning up

In [20]:
df.fillna({"OrderID": 0},inplace=True) #fill missing values with 0 in OrderID column

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,xyz,Furniture,1,35.0,2024-07-11,Yes,Ukraine